HW04 LRU cache
altynbaev/home_work pull request #4
Opened 2023-07-12 12:25 UTC by altynbaev

2023-07-13 13:09 UTC, vladislavmass requested changes
Отличное начало. Радует что реализована Clear за O(1). Работу пока принять не могу так как 2 связный список паникует. Для подтверждения бага нужно добавить в него ровно 1 элемент и потом его удалить.

2023-07-13 13:09 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	cache.capacity = 0
Капасити кэша не должно меняться при очистки. Предлагаю эту строчку убрать

2023-07-13 13:09 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +		item.Next = nil
Для указателей nil значение по умолчанию. Поэтому данные строчки ничего не делают

2023-07-13 13:17 UTC, altynbaev commented on hw04_lru_cache/cache.go
> +	cache.capacity = 0
Согласен, ошибся

2023-07-13 13:25 UTC, altynbaev commented on hw04_lru_cache/list.go
> +		item.Next = nil
Спасибо, не обратил внимания

2023-07-14 08:57 UTC, vladislavmass approved these changes
Отлично. Правки есть, тесты есть. Работа принята 10/10

2023-07-14 08:57 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +type LinkedList struct {
Изначальная идея была в том, что и структура и поля приватные, а конструктор возвращает просто интерфейс.

2023-07-14 10:58 UTC, merged