HW05 Implement parallel execution
altynbaev/home_work pull request #5
Opened 2023-07-21 15:35 UTC by altynbaev

2023-07-22 04:55 UTC, vladislavmass requested changes
Работа хоршая. Радует что используется `mu` и `waitGroup`. Код вполне рабочий. Но принять работу немогу. Написано очень мало тестов, а также алгоритм работы очень сложный. За тест могу дать всего 1 бал из 4. 

Например я бы хотел увидить тест, где за место Tаска передается nil. Сейчас данный тест кейс приведет к панике.

Также очень хотелось бы увидеть оптимизацию связную с передачей пустого списка тасков

2023-07-26 03:57 UTC, vladislavmass requested changes
Код стал лучше. Но я все еще не понимаю почему вначале идет проверка на то, что чилос ошибок больше или равно каунт, а только потом идет инкремент. Лучше поменять эти 2 блока, что бы убрать 1 лишнее выполнение задачи.

2023-07-26 07:15 UTC, altynbaev commented
Инкремент числа ошибок идет после выполнения задачи, если она вернула ошибку. А проверка на то, что число ошибок больше или равно максКаунт делается до выполнения задачи. Что не так? Если делать инкремент до проверки, то все равно нужно выполнить задачу, чтобы проверить, что она вернула ошибку

2023-07-26 19:04 UTC, vladislavmass approved these changes
Хорошая работа. Принято. 9/10. -1 бал за использование буферезированного канала размером с массив тасков. Этого можно избежать если писать задачи в канал после запуска горутин обработчиков.

2023-07-26 20:57 UTC, altynbaev commented
Внес исправления для использования небуферизованного канала.

2023-07-27 15:23 UTC, merged

2023-07-27 15:24 UTC, HangryHoneyBadger approved these changes
Отличная работа. Классный тест вышел по итогу на многопоточность)

2023-07-27 16:25 UTC, altynbaev commented
> Отличная работа. Классный тест вышел по итогу на многопоточность)

Спасибо)