Implement HW07 file copying
altynbaev/home_work pull request #7
Opened 2023-08-15 23:02 UTC by altynbaev

2023-08-16 06:28 UTC, vladislavmass requested changes
Хорошее начало. Этот код хорошо справится с копированием мелких файлов. Но что будет если пользователь будет копировать большие файлы.

2023-08-16 06:28 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +			fmt.Println(fmt.Errorf("close source file error: %w", err))
Непонятно зачем создавать новую ошибку и потом сразу ее выводить.Предлагаю вывести этот текст сразу без создания новой ошибке.

2023-08-16 06:28 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +			fmt.Println(fmt.Errorf("close target file error: %w", err))
Непонятно зачем создавать новую ошибку и потом сразу ее выводить.Предлагаю вывести этот текст сразу без создания новой ошибке.

2023-08-16 06:28 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		_, err = io.CopyN(targetFile, barReader, limit)
А что если пользователь решит с помощью этой утилиты скопировать фильм 4k hdr весом гигабайт под 40 без лимитов.

2023-08-16 11:15 UTC, altynbaev commented on hw07_file_copying/copy.go
> +			fmt.Println(fmt.Errorf("close source file error: %w", err))
Чтобы обогатить контекстом, в котором возникла эта ошибка. В чем минусы данного подхода?

2023-08-16 18:58 UTC, altynbaev commented on hw07_file_copying/copy.go
> +		_, err = io.CopyN(targetFile, barReader, limit)
Фнкция io.Copy, если реализованы ReaderFrom и WriterTo (а для файловых операций с диском это так), позволяет производить копирование не прогоняя данные через программу. Если ReaderFrom и WriterTo не реализованы, то io.Copy производит копирование с использованием буфера в 32кБ

2023-08-16 19:00 UTC, altynbaev commented on hw07_file_copying/copy.go
> +			fmt.Println(fmt.Errorf("close source file error: %w", err))
Сделал вывод сразу

2023-08-16 20:36 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		_, err = io.CopyN(targetFile, barReader, limit)
Согласен

2023-08-16 20:46 UTC, vladislavmass requested changes
Стало лучше. Но прогресс не работает в случае если limit не задан

2023-08-16 20:46 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	bar := pb.Full.Start64(limit)
Если limit будет равен 0, то прогресс бар не будет работать. Так как его максимально значение будет равно 0

2023-08-16 21:47 UTC, altynbaev commented on hw07_file_copying/copy.go
> +	bar := pb.Full.Start64(limit)
Поправил

2023-08-17 08:20 UTC, vladislavmass approved these changes
Принято. 10/10

2023-08-17 08:23 UTC, merged