Implement hw10
altynbaev/home_work pull request #8
Opened 2023-10-01 21:37 UTC by altynbaev

Бенчмарки

До:
```
goos: darwin
goarch: amd64
pkg: github.com/fixme_my_friend/hw10_program_optimization
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkResults-12    	     100	  10346374 ns/op	 3239703 B/op	   31461 allocs/op
PASS
ok  	github.com/fixme_my_friend/hw10_program_optimization	2.813s
```

После:
```
goos: darwin
goarch: amd64
pkg: github.com/altynbaev/home_work/hw10_program_optimization
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkResults-12    	     100	   2947835 ns/op	  172244 B/op	   14473 allocs/op
PASS
ok  	github.com/altynbaev/home_work/hw10_program_optimization	0.810s
```

2023-10-02 16:36 UTC, vladislavmass requested changes
Хорошее начало, но есть потенциальная паника

2023-10-02 16:36 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  			num := result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]
Если в почте не будет @ (ошиблись при вводе) то код упадет с паникой

2023-10-02 17:20 UTC, altynbaev commented on hw10_program_optimization/stats.go
>  			num := result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]
Да, поправил

2023-10-03 09:28 UTC, vladislavmass approved these changes
Отлично. Принято

2023-10-03 09:56 UTC, merged