Hw11 telnet client
altynbaev/home_work pull request #9
Opened 2023-10-07 22:43 UTC by altynbaev

2023-10-09 18:55 UTC, vladislavmass requested changes
Хорошее начало, но в работе есть потенциальная паника

2023-10-09 18:55 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	go func() {
Это ничем не отличается от sigkil. Так делать не надо. sigint передается что бы программа успела нормально заверишить свою работу

2023-10-09 18:55 UTC, vladislavmass commented on hw11_telnet_client/telnet.go
> +	return c.connection.Close()
Если перед вызовом Close не вызвали Connect то будет паника.

2023-10-09 20:32 UTC, altynbaev commented on hw11_telnet_client/main.go
> +	go func() {
Поправил

2023-10-09 20:33 UTC, altynbaev commented on hw11_telnet_client/telnet.go
> +	return c.connection.Close()
Поправил

2023-10-12 05:50 UTC, vladislavmass approved these changes
Отличная работа. Принято.

2023-10-12 07:15 UTC, merged